
services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped